flags: {}
packages:
    - '.'

extra-deps:
    - samtools-0.2.4.1
    - conduit-combinators-1.0.3.1
    - chunked-data-0.2.0
    - mono-traversable-0.10.2
    - dlist-instances-0.1

resolver: nightly-2016-05-27
